---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-alert-config
  namespace: monitoring
spec:
  encryptedData:
    bot_token: AgCbE4YhvqO0KQp9Mt441/Oj6s16v/k1Rgy9/lIWnLju0GHSCmZ0qkqmxwfM22sw7S7r2obWzT5CQQGSha8eHDDpVbq1qxMXMJS+zvyn5Cru7K2A2pjSof0m5uyp3FtLyBxHFFSnTGKz2sFlo8bu/O2zm2tqxxoHfvsBMTwbTXHKXED0WLOKg2h4gczC3MFjvehXhKMycSqESbhcwuGvnOK+cUKoN1J7Rf+kOAmpLtn+PgB3KsMZqbxzu9cdDEXctilgTQNEg4uNG0dG9z5bbtHn6Q6Z0SvpWYCPSENUuUkS0eohD5AHyQuKOe7Qm6T9dgjREFRRXWyJTjCKKxVlSCITXbPevLiA6gUBsRtM2EwIB6FT/bxuiN3Qgg610jTlhZXPQD0XOspD51MCksDaVUL7eIkPHfBeC+GwJDt8zvDI+EzcJO4NaxPUwgU7/IM3BdePRfpUT5lUyrJQVUJBr0XjwuKix6dymtEXRveTEReIal0317wQ8SKCELgIXFr3CI6DSs4iZ4gfpG26ezFEolPkC1E81JBr0iMP8O7w0IfDn2Xpq//ZGfD17XVL8DM3rKmbS+lfPHA067Mi/dSGWGTIf51/5pvQUiiRv9Wh8Fgg1wlMtYbI3hmZeuYLvwmyifurMiyTDQjtmxOXCJNnJf8T6D7LWwMbk/KEhWAtuuPEszYsdEqg22Q09cqyMAuw7RyhWDFtoodtVQGH+6zE5QBKJJ6OTic8QVEzNL9lijO6m/n8nDxGe7kyUi9uO7ab
    chat_id: AgAZNss+mbH+eTMGRI0p9AFLSgmmca3UhnT9fNozCZeldxAVlyTY8L55T8gcmORklQnWy9fPbJfcib1CyQcdbbWRDNTit2nhwbGLw95NSf1Rr72aeWCIPP16eNnaZWtAB+IGVAz3ZLrfV7eJoFzNmJBb0nm/I5Mj1fM4AykW9lRk6/w1DEjBzkj9s9fZh3d7VSbMC8RzpcrIk3e3Sst/WCe7F2+44RxoL5vYe4k4jC4GLtGGk18v1AVYzBKZapehK5SjqZv78likiLQApT1DStfHcGvy7tBazk6WX3yWZtzhEVH1GABXaUgTKZqb5mMQyYX8ZkoVzIJIHDl5vDbjU9BSclqL6mDhDT1CkOklhQkFrVkJwmCMmCRFY+7BHCmWcRn4FBTBsP/qQhBKifIxpYjeNq0HIc9bVYmK8Qbwg1MGd/q7FVAx9riBrTW//MLxFkkUpBvHyUaIh1HmNoNBcAp3ophmO/fOTvAmb9+Q7vTJ72jC/FgxGDVCizrAcDHrDAvNlOjlfkvR/4nDxrfHASQsk/nzMu40wH3Rlh2Ozofsj1b4LvR+iDor7RDIjECIljGQpMiWLKdVwP//N8jIl5uFzZcYAa8TGdxsc9MfDxAEOTAvC7L0UbQMCD9Vb/jnvbWPwjYzL1kMnNrD9Zg5UpipDVRG4rsCk72XN6YXDyG0TE8HKtPw8vMiBS6xWYubCYj3WLuLoS3rUWqH
  template:
    metadata:
      name: telegram-alert-config
      namespace: monitoring
    type: Opaque
