---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-alert-config
  namespace: monitoring
spec:
  encryptedData:
    bot_token: AgCevsoGLBzdFbMz3eRZv7ZoLuF6Rfvo9nmk/E8eYrqRKGpYCkb88T0qAfKPbYJhN84yNC5ar6e487Qz/Tw+VXqgpeeRuwrZSW1agLDrKTWY1y+raA/Gwz3nbfibF1m3EX6L2qG4wD3E1W0sUS7wYQe6E88F27gxZI1WcPWmG1oKnavTCVByhWrl3hCiCHWKPF/FNqXSxDdKx1n9JCldvEPqP075+w3uiTB/JR5fdJDCdRwO3AX4FRWb7ycbxAb0O6mcC3g/fd9evLE76aTkbCjXJOKkOeLhJTHqqf+0t+h0FgVUTkwqf4w0W70BoKb1W3IgJ7ucYyH9rgAYgvUHM2k3hxkKzMnz0wDDQq1UAiowJirM6276DZpthsks24FTr6vRzwPZssMBBuiAgO9utdQAHWPMhxJLrR2lORPaerSrCuQgAgj7brEzMS+f5Ptcfgrl/dq2gnQdpk1R4e+vOjSUK6Nkn7r6bjtZTS2MFXNkxEKqiOQDI7JebDthepW7NVQGubfIz3gTjCIpbmAaP+6Llsawr8DTNwSVsZlKJdMLpFf0h0fQmv454PeSX7/rcztF2dhi75gUIO3JkpOQuOD6n8nVzAGOOvzZ1+mQE5RJGUE9Vmo+ZDrfl8WQusAhNHV3+f4y/tXklMxqrF9NFBsrCZM336XoHdChVR5iTnPMCtXKNYWez1fVcqJtIytO4eMC3lvlvXNYUa9nunkBky6ifAB64pYA7+8zgROPNSSMmCZm/13CXTNllfVugcH0
    chat_id: AgB6oA+YnuvT2vAa7X6l+8Wd4QbJPWMs1vAL6nqSQwq9LJZHfksz4lks5HXcdfUWbdb+BkXtHNL6i/1Wqbl/Zag67pQWLHLInqt3bmVcujMdEf2UBE8UPVA1Y1O/lsw0dRAV+7m8zUkq0XVDT7IX79uuGQJtAxM87y0rlINNyAYjchlpXVoPWklaqgN+w/w9S2A3gK8GYPK6KS9E6uIDnLV6UTnq2NLMa9gVY/kq7sr8BacbnXnN/Mx5sJX7F5oMBhRLEwtCoZDVlFtlR7YQxfTqFgHPCDX5Pb6fp0O2OeDOPbNVCve+McR7bNSwxdE67yqoX+dhHPdjwqkUgiW+U2xGg4hFWpU1zzJSVoyXQ+23F9WUFDNvyBgNb38Tc3TBU4ubx0T2f+huCNqtalZoQLFgZV4cbTwxaqKpx0xlO3pBOraXY+IMUdRY7EIX7XO6EAW/qmLPI+/bG0n7RGKxA4s9VBQwQFkjTIb3JqCtFC/VxiWzgymmjNbcKQT7SX6LBL8iDJF9JgxTDihPxxNGSVTl9dbCb6GLobYU8ePDcX0iYzl+Yc+WlyIapnEpSuIP87cKeCzNrsvjgPGlGs0HRs/4PVOM2sjDqKpplCayZHExQORxpXIWDu5WI9e9Na7MfNaPm3xHbJP3fXu/jg78KQ9268HPWyLsyYgASS9O96A3SgC5w7O4aNcYRS3vacDQUcXkn7GZZzPle0zOfA==
  template:
    metadata:
      name: telegram-alert-config
      namespace: monitoring
    type: Opaque
