---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: whatsapp-alert-config
  namespace: monitoring
spec:
  encryptedData:
    target_number: AgB0Zc1oMCUIuLfuuMI1kpOLXQl9FRpowLNWmPMpO16v28GvGe6wA6RFbtXvtRl4JtkEFi5HRWWKqVdX0LJjYmM/3D7n9fvW+QjPSP4LPiTVCV3audIXDWegy/4tppH8IFcZx/DS2SZabSnCyna9h4fDk+/Cm9ka7nu+TrS/+WbkrEX5CCB1SQmfT+SJJqHWyx4fPeQFknorgawORiPHjTNOsHUQxrAhilUfXpCZ8SZ7z2bt+yPuHH2l0+SeezyulKE+0bDE6NI/g0XgxBfkufl+qh3qffQWP/ujwaWCbbSL2/9W/DO29paCzHkfD4zwxxQtFloQD1k92CrMjBTHYvh4w367GgdGwA3BSmzSbtD1YghCIfxR9GnxFOE6DyUSrWJSLcrxA6fDwmiey8eK87EapuYjnjAchIV+ihpXeomR6KvCBYvX9SKaUneF2uA1DxvGAYWeK1a1UIeuSVzqemXI1MmAcrQadMmXCCU+WLnte/SWBWCBDCG7mteULaW3IwT8rKIdABrDE3Tcs0+jkmuBIKvLw2MsNKxRmQmBnNVfzNj3fnkmWR/+I2S96Fm49Vr8EqB8Tplgh6luqx7cSzWFkcIoiMP3Nf3pfSzW4S30YqmKVkEaANwR04ZUNytBMnrD3LfheEmmwqcIjmFdFgTqV6q4ksZZw9VEd/olwNAvhq9E7GKJJo/H3fN8y57Uj/l6u/XXp+jbmwLzUpaX
  template:
    metadata:
      name: whatsapp-alert-config
      namespace: monitoring
    type: Opaque
